Add support and doc for AD579x DAC
analogdevicesinc/PrecisionToolbox pull request #14
Opened 2023-12-20 07:17 UTC by SaikiranGudla

Add precision toolbox support for AD5760, AD5780,
AD5781, AD5790, AD5791 DACs

2023-12-20 07:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/analogdevicesinc/PrecisionToolbox?pullRequest=14) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/analogdevicesinc/PrecisionToolbox?pullRequest=14) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/analogdevicesinc/PrecisionToolbox?pullRequest=14) it.</sub>

2024-01-08 21:26 UTC, tfcollins commented on +adi/+AD5760/Tx.m
> +        Raw
All properties should have a default value with docstrings

2024-01-08 21:27 UTC, tfcollins commented on +adi/+AD5760/Tx.m
> +                obj.setDeviceAttributeRAW('sampling_frequency', num2str(value));            end
Can you move the "end" to the next line

2024-01-08 21:27 UTC, tfcollins commented on +adi/+AD5760/Tx.m
> +        PowerDown
This should be a Logical

2024-01-08 21:27 UTC, tfcollins commented on +adi/+AD5760/Tx.m
> +            end
If you define PowerDown as a Logical this check is done for you.

2024-01-08 21:31 UTC, tfcollins requested changes
All the child classes are almost identical except for the device names. You should instead put all the properties in the base class an update the devName+phyDevName in the constructor calls. This greatly simplifies the code

2024-01-09 03:45 UTC, ribdp commented on +adi/+AD5781/Tx.m
> +                function set.CodeSelect(obj, value)
Indentation is a bit off

2024-01-12 10:55 UTC, SaikiranGudla commented
> All the child classes are almost identical except for the device names. You should instead put all the properties in the base class an update the devName+phyDevName in the constructor calls. This greatly simplifies the code

Yes, except for the device names, and resolution (data type), all the generics are almost identical. Do you suggest using a single Tx class for all the generics with the device name as an argument?

2024-01-18 09:17 UTC, SaikiranGudla commented
v1.0: Addressed review comments

1. Moved all the properties to the base class and updated the devName, phyDevName, and dataType in the constructor calls
2. Defined PowerDown as logical
3. Added comments for properties

2024-01-22 23:47 UTC, tfcollins commented on +adi/+AD579x/Base.m
> +         SamplesPerFrame
Please provide a default value

2024-01-22 23:48 UTC, tfcollins requested changes
Just update the SamplesPerFrame and this is ready to merge

2024-01-23 05:30 UTC, SaikiranGudla commented
v 1.1: Addressed review comments

Added default value for SamplesPerFrame

2024-01-24 04:40 UTC, merged