Add cn0585_fmcz support
analogdevicesinc/PrecisionToolbox pull request #5
Opened 2023-07-05 09:02 UTC by StancaPop

Add all the necessary files for targeting support. Add support for the cn0585_fmcz hdl design for both targeting and streaming.

This PR also deletes the CI/scripts folder as it will use the submodule from the ToolboxCI repo. The updates have been tested along with Vivado 2022.2 and Matlab R2022a.

2023-07-05 17:39 UTC, tfcollins commented on test/CN0585_streaming_test.m
This is an example and should be in such a folder, not under tests

2023-07-05 20:37 UTC, tfcollins requested changes
Do you need the hdl/common folder?

2023-07-05 20:38 UTC, tfcollins commented on +adi/+AD3552R/Tx.m
> +        StreamStatus = 'stop_stream';
All public properties need to be documented

2023-07-05 20:39 UTC, tfcollins commented on +adi/+CN0585/Rx.m
> +    end
Remove

2023-07-05 20:39 UTC, tfcollins commented on +adi/+CN0585/Tx0.m
> +    end
Remove

2023-07-05 20:40 UTC, tfcollins commented on +adi/+CN0585/Tx1.m
> +    end
Remove

2023-07-05 20:40 UTC, tfcollins commented on +adi/+AD3552R/Base.m
> +        OutputRange = '-10/+10V';
All public properties need to be documented

2023-10-05 05:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/analogdevicesinc/PrecisionToolbox?pullRequest=5) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/analogdevicesinc/PrecisionToolbox?pullRequest=5) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/analogdevicesinc/PrecisionToolbox?pullRequest=5) it.</sub>

2023-10-30 20:57 UTC, tfcollins commented on test/NonHWTest.m
Remove

2023-10-30 20:58 UTC, tfcollins commented on test/DemoTests.m
Remove

2023-10-30 20:59 UTC, tfcollins commented on test/runDemoTests.m
Remove

2023-10-30 20:59 UTC, tfcollins commented on test/runNonHWTest.m
Remove

2023-10-30 21:02 UTC, tfcollins reviewed
Remove some of the extra files that are unused.

You probably want to add the BSPTests class from TRX or HSX to get the targeting pieces working in CI

2023-11-02 08:53 UTC, StancaPop commented on test/NonHWTest.m
Done.

2023-11-02 08:53 UTC, StancaPop commented on test/DemoTests.m
Done.

2023-11-02 08:54 UTC, StancaPop commented on test/runDemoTests.m
Done.

2025-02-04 15:51 UTC, closed without merging

2025-02-04 15:52 UTC, StancaPop commented
Will open a clean PR for this project.